export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INVALID_DATE: "INVALID_DATE",
  SEAT_NOT_AVAILABLE: "SEAT_NOT_AVAILABLE",
  HOLD_EXPIRED: "HOLD_EXPIRED",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
