import {
  brandPaletteToCssVars,
  generateBrandPalette,
  type CmsSiteBundleDto,
} from "@repo/shared";

const FALLBACK_PRIMARY = "#2e7d32";
const FALLBACK_PALETTE = generateBrandPalette(FALLBACK_PRIMARY);
const FALLBACK_UPDATED = "2020-01-01T00:00:00.000Z";

/** Static fallback when CMS API is unavailable — mirrors seed defaults. */
export const DEFAULT_CMS_SITE_BUNDLE: CmsSiteBundleDto = {
  profile: {
    companyName: "Shahzadpur Travels",
    tagline: "TRAVELS",
    logoUrl: "/images/logo/logo.png",
    faviconUrl: null,
    tradeLicenseNo: "08-032-01046",
    status: "PUBLISHED",
    updatedAt: FALLBACK_UPDATED,
  },
  theme: {
    primaryColor: FALLBACK_PRIMARY,
    fontFamily: "Inter",
    palette: FALLBACK_PALETTE,
    status: "PUBLISHED",
    updatedAt: FALLBACK_UPDATED,
  },
  footer: {
    contactLines: [
      { icon: "pin", text: "Dawriapur Bazar" },
      { icon: "home", text: "Shahzadpur-6770" },
      { icon: "building", text: "Shahzadpur" },
      { icon: "globe", text: "Sirajganj" },
    ],
    email: "shahzadpurtravels1980@gmail.com",
    paymentBannerUrl: "/images/home/ssl-commerz-inline.png",
    barLinks: [
      { label: "About Us", href: "/about" },
      { label: "Return Policy", href: "/return-policy" },
      { label: "Terms & Conditions", href: "/terms-and-conditions" },
      { label: "Privacy Policy", href: "/privacy-policy" },
    ],
    poweredByText: "Powered By: Shahzadpur Travels",
    status: "PUBLISHED",
    updatedAt: FALLBACK_UPDATED,
  },
  media: {
    hero: {
      id: "fallback-hero",
      kind: "HERO",
      url: "/images/home/hero.jpg",
      alt: "Shahzadpur Travels coach on the highway",
      sortOrder: 0,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    featured: [
      {
        id: "fallback-featured-0",
        kind: "FEATURED",
        url: "/images/home/bus-1.jpg",
        alt: "Coach fleet 1",
        sortOrder: 0,
        status: "PUBLISHED",
        updatedAt: FALLBACK_UPDATED,
      },
      {
        id: "fallback-featured-1",
        kind: "FEATURED",
        url: "/images/home/bus-2.jpg",
        alt: "Coach fleet 2",
        sortOrder: 1,
        status: "PUBLISHED",
        updatedAt: FALLBACK_UPDATED,
      },
      {
        id: "fallback-featured-2",
        kind: "FEATURED",
        url: "/images/home/bus-3.jpg",
        alt: "Coach fleet 3",
        sortOrder: 2,
        status: "PUBLISHED",
        updatedAt: FALLBACK_UPDATED,
      },
      {
        id: "fallback-featured-3",
        kind: "FEATURED",
        url: "/images/home/bus-4.jpg",
        alt: "Coach fleet 4",
        sortOrder: 3,
        status: "PUBLISHED",
        updatedAt: FALLBACK_UPDATED,
      },
    ],
    footerPayment: {
      id: "fallback-footer-payment",
      kind: "FOOTER_PAYMENT",
      url: "/images/home/ssl-commerz-inline.png",
      alt: "Pay with Visa, Mastercard, bKash, Nagad, and other methods. Verified by SSLCommerz",
      sortOrder: 0,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
  },
  featuredRoutes: [
    {
      id: "fallback-route-0",
      routeId: "fallback",
      routeSlug: "dhaka-pabna",
      fromStop: { city: "DHAKA", name: "Dhaka" },
      toStop: { city: "PABNA", name: "Pabna" },
      sortOrder: 0,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-1",
      routeId: "fallback",
      routeSlug: "dhaka-shahzadpur",
      fromStop: { city: "DHAKA", name: "Dhaka" },
      toStop: { city: "SHAHZADPUR", name: "Shahzadpur" },
      sortOrder: 1,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-2",
      routeId: "fallback",
      routeSlug: "dhaka-iswardi",
      fromStop: { city: "DHAKA", name: "Dhaka" },
      toStop: { city: "ISWARDI", name: "Iswardi" },
      sortOrder: 2,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-3",
      routeId: "fallback",
      routeSlug: "dhaka-chatmohor",
      fromStop: { city: "DHAKA", name: "Dhaka" },
      toStop: { city: "CHATMOHOR", name: "Chatmohor" },
      sortOrder: 3,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-4",
      routeId: "fallback",
      routeSlug: "dhaka-chattogram",
      fromStop: { city: "DHAKA", name: "Dhaka" },
      toStop: { city: "CHATTOGRAM", name: "Chattogram" },
      sortOrder: 4,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-5",
      routeId: "fallback",
      routeSlug: "narayangonj-pabna",
      fromStop: { city: "NARAYANGONJ", name: "Narayanganj" },
      toStop: { city: "PABNA", name: "Pabna" },
      sortOrder: 5,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-6",
      routeId: "fallback",
      routeSlug: "narayangonj-shahzadpur",
      fromStop: { city: "NARAYANGONJ", name: "Narayanganj" },
      toStop: { city: "SHAHZADPUR", name: "Shahzadpur" },
      sortOrder: 6,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-7",
      routeId: "fallback",
      routeSlug: "pabna-narayangonj",
      fromStop: { city: "PABNA", name: "Pabna" },
      toStop: { city: "NARAYANGONJ", name: "Narayanganj" },
      sortOrder: 7,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-8",
      routeId: "fallback",
      routeSlug: "pabna-chattogram",
      fromStop: { city: "PABNA", name: "Pabna" },
      toStop: { city: "CHATTOGRAM", name: "Chattogram" },
      sortOrder: 8,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-9",
      routeId: "fallback",
      routeSlug: "pabna-coxs-bazar",
      fromStop: { city: "PABNA", name: "Pabna" },
      toStop: { city: "COX'S BAZAR", name: "Cox's Bazar" },
      sortOrder: 9,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-10",
      routeId: "fallback",
      routeSlug: "pabna-sylhet",
      fromStop: { city: "PABNA", name: "Pabna" },
      toStop: { city: "SYLHET", name: "Sylhet" },
      sortOrder: 10,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
    {
      id: "fallback-route-11",
      routeId: "fallback",
      routeSlug: "sylhet-iswardi",
      fromStop: { city: "SYLHET", name: "Sylhet" },
      toStop: { city: "ISWARDI", name: "Iswardi" },
      sortOrder: 11,
      isVisible: true,
      status: "PUBLISHED",
      updatedAt: FALLBACK_UPDATED,
    },
  ],
};

export function defaultThemeCssVars(): Record<string, string> {
  return brandPaletteToCssVars(FALLBACK_PALETTE);
}
